# -*- coding: utf-8 -*-
"""FML Group project_Test 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MW9pOVxdbopQnwS5d2wWB199-9yR6Jg7
"""

import os
from pathlib import Path
import pandas as pd
import numpy as np

!pip install wrds

"""After installing the `wrds` library, you can connect to WRDS and fetch data. You will be prompted to enter your WRDS username and password."""

import wrds

MARKETS = [
    "USA",
    "Japan",
    "China",
    "India",
    "Korea",
    "Hong_Kong",
    "Taiwan",
    "France",
    "United_Kingdom",
    "Thailand",
    "Australia",
    "Singapore",
    "Sweden",
    "South_Africa",
    "Poland",
    "Israel",
    "Vietnam",
    "Italy",
    "Turkey",
    "Switzerland",
    "Indonesia",
    "Greece",
    "Philippines",
    "Norway",
    "Sri_Lanka",
    "Denmark",
    "Finland",
    "Saudi_Arabia",
    "Jordan",
    "Egypt",
    "Spain",
    "Kuwait",
]

MARKET_TO_EXCNTRY = {
    "USA": "USA",
    "Japan": "JPN",
    "China": "CHN",
    "India": "IND",
    "Korea": "KOR",
    "Hong_Kong": "HKG",
    "Taiwan": "TWN",
    "France": "FRA",
    "United_Kingdom": "GBR",
    "Thailand": "THA",
    "Australia": "AUS",
    "Singapore": "SGP",
    "Sweden": "SWE",
    "South_Africa": "ZAF",
    "Poland": "POL",
    "Israel": "ISR",
    "Vietnam": "VNM",
    "Italy": "ITA",
    "Turkey": "TUR",
    "Switzerland": "CHE",
    "Indonesia": "IDN",
    "Greece": "GRC",
    "Philippines": "PHL",
    "Norway": "NOR",
    "Sri_Lanka": "LKA",
    "Denmark": "DNK",
    "Finland": "FIN",
    "Saudi_Arabia": "SAU",
    "Jordan": "JOR",
    "Egypt": "EGY",
    "Spain": "ESP",
    "Kuwait": "KWT",
}

MARKET_PERIODS = {
    "USA": ("1963-01-01", "2017-12-31"),
    "Japan": ("2008-01-01", "2017-12-31"),
    "China": ("1999-01-01", "2017-12-31"),
    "India": ("2007-01-01", "2017-12-31"),
    "Korea": ("1997-01-01", "2017-12-31"),
    "Hong_Kong": ("1997-01-01", "2017-12-31"),
    "Taiwan": ("2007-01-01", "2017-12-31"),
    "France": ("1995-01-01", "2017-12-31"),
    "United_Kingdom": ("2005-01-01", "2017-12-31"),
    "Thailand": ("1997-01-01", "2017-12-31"),
    "Australia": ("2008-01-01", "2017-12-31"),
    "Singapore": ("2007-01-01", "2017-12-31"),
    "Sweden": ("2001-01-01", "2017-12-31"),
    "South_Africa": ("1997-01-01", "2017-12-31"),
    "Poland": ("2006-01-01", "2017-12-31"),
    "Israel": ("2005-01-01", "2017-12-31"),
    "Vietnam": ("2010-01-01", "2017-12-31"),
    "Italy": ("2001-01-01", "2017-12-31"),
    "Turkey": ("2006-01-01", "2017-12-31"),
    "Switzerland": ("2002-01-01", "2017-12-31"),
    "Indonesia": ("2005-01-01", "2017-12-31"),
    "Greece": ("2006-01-01", "2017-12-31"),
    "Philippines": ("2006-01-01", "2017-12-31"),
    "Norway": ("2007-01-01", "2017-12-31"),
    "Sri_Lanka": ("2010-01-01", "2017-12-31"),
    "Denmark": ("2007-01-01", "2017-12-31"),
    "Finland": ("2007-01-01", "2017-12-31"),
    "Saudi_Arabia": ("2010-01-01", "2017-12-31"),
    "Jordan": ("2009-01-01", "2017-12-31"),
    "Egypt": ("2010-01-01", "2017-12-31"),
    "Spain": ("2011-01-01", "2017-12-31"),
    "Kuwait": ("2012-01-01", "2017-12-31"),
}

ID_VARS = [
    "id",
    "eom",
    "excntry",
    "gvkey",
    "permno",
    "size_grp",
    "ret_exc_lead1m",
]

direct_factors = [
    "taccruals_at",      # absolute accruals
    "nwc_at",            # working capital accruals
    "taccruals_ni",      # percent accruals
    "at_gr1",            # asset growth
    "be_gr1",            # growth in common shareholder equity
    "debtlt_gr1a",       # growth in long-term debt
    "sale_gr1",          # sales growth
    "be_me",             # book-to-market
    "ocf_me",            # cash-flow-to-price
    "ni_me",             # earnings-to-price
    "sale_me",           # sales-to-price
    "div12m_me",         # dividend yield
    "ocf_debt",          # cash-flow-to-debt
    "at_be",             # leverage
    "ni_be",             # return on equity
    "ret_12_1",          # 12-month momentum
    "ret_6_1",           # 6-month momentum
    "ret_1_0",           # 1-month reversal
    "turnover_126d",     # share turnover
    "dolvol",            # dollar trading volume
    "dolvol_var_126d",   # volatility of dollar trading volume
    "turnover_var_126d", # volatility of share turnover
    "ami_126d",          # illiquidity
    "rvol_21d",          # return volatility
    "rmax1_21d"          # maximum daily return
]

ALL_COLS = ID_VARS + direct_factors

def sql_list(items):
    return ", ".join(f"'{x}'" for x in items)

def check_columns_exist(db, table="contrib.global_factor"):
    """Optional sanity check: confirm all requested columns exist."""
    describe = db.describe_table(library="contrib", table="global_factor")
    available = set(describe["name"].str.lower())
    requested = set(c.lower() for c in ALL_COLS)
    missing = sorted(requested - available)
    if missing:
        raise ValueError(
            "These requested columns were not found in contrib.global_factor:\n"
            + ", ".join(missing)
        )
    print("All requested columns found.")

def make_query_for_country(country_name, trim_to_paper_period=True):
    excntry = MARKET_TO_EXCNTRY[country_name]
    col_sql = ", ".join(ALL_COLS)

    where = [
        "common = 1",
        "exch_main = 1",
        "primary_sec = 1",
        "obs_main = 1",
        f"excntry = '{excntry}'",
    ]

    if trim_to_paper_period:
        start_date, end_date = MARKET_PERIODS[country_name]
        where.append(f"eom >= '{start_date}'")
        where.append(f"eom <= '{end_date}'")

    query = f"""
        SELECT {col_sql}
        FROM contrib.global_factor
        WHERE {" AND ".join(where)}
        ORDER BY eom, id
    """
    return query

def download_one_country(db, country_name, out_dir="paper32_data", parquet=True):
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    print(f"Downloading {country_name} ...")
    query = make_query_for_country(country_name, trim_to_paper_period=True)
    df = db.raw_sql(query, date_cols=["eom"])

    # Add paper market name explicitly
    df["market_name"] = country_name

    file_base = out_path / country_name
    if parquet:
        df.to_parquet(f"{file_base}.parquet", index=False)
        print(f"Saved {country_name} -> {file_base}.parquet | rows={len(df):,}")
    else:
        df.to_csv(f"{file_base}.csv", index=False)
        print(f"Saved {country_name} -> {file_base}.csv | rows={len(df):,}")

    return df

def download_all_countries_separately(out_dir="paper32_data", parquet=True):
    db = wrds.Connection()
    try:
        check_columns_exist(db)
        for country in MARKETS:
            download_one_country(db, country, out_dir=out_dir, parquet=parquet)
    finally:
        db.close()

def validate_download(df):
    print("\nBasic validation:")
    print(df[["market_name", "excntry"]].drop_duplicates().sort_values("market_name"))
    print("\nDate range by market:")
    print(
        df.groupby("market_name")["eom"]
        .agg(["min", "max", "count"])
        .sort_values("count", ascending=False)
    )

    missing_chars = df[direct_factors].isna().mean().sort_values(ascending=False)
    print("\nTop 10 missing-rate characteristics:")
    print(missing_chars.head(10))

import wrds

# Establish a connection to WRDS
# You will be prompted for your WRDS username and password
db = wrds.Connection()

try:
    print("Listing available columns in contrib.global_factor...")
    describe = db.describe_table(library="contrib", table="global_factor")
    available_columns = describe["name"].str.lower().tolist()
    print("\nAvailable columns in 'contrib.global_factor':")
    print(sorted(available_columns))

    print("\nOriginal requested characteristics (direct_factors):")
    print(sorted([c.lower() for c in direct_factors]))

    missing_from_db = sorted(set([c.lower() for c in direct_factors]) - set(available_columns))
    if missing_from_db:
        print(f"\nThese characteristics from direct_factors were NOT found in the database:")
        print(missing_from_db)
    else:
        print("\nAll characteristics from direct_factors were found in the database.")

    print("\nPlease adjust the direct_factors list to only include columns available in 'contrib.global_factor'.")
    print("Once adjusted, you can uncomment and run the original 'download_all_countries_separately' call.")

finally:
    db.close()

# Original call (commented out for diagnostic purposes)
# download_all_countries_separately(out_dir="paper32_data", parquet=True)

# Establish a connection to WRDS
# You will be prompted for your WRDS username and password
db = wrds.Connection()
print("Successfully connected to WRDS!")

db.describe_table(library="contrib", table="global_factor")

db = wrds.Connection()
df_usa = download_one_country(db, "USA", out_dir="paper32_data", parquet=True)
db.close()

display(df_usa.head ())

from google.colab import files

files.download('paper32_data/USA.parquet')

db = wrds.Connection()
df_usa_csv = download_one_country(db, "USA", out_dir="paper32_data", parquet=False)
db.close()

from google.colab import files

files.download('paper32_data/USA.csv')

db = wrds.Connection()
df_usa = download_one_country(db, "Vietnam", out_dir="paper32_data", parquet=False)
db.close()

from google.colab import files

files.download('paper32_data/Vietnam.csv')

db = wrds.Connection()
df_usa = download_one_country(db, "Turkey", out_dir="paper32_data", parquet=False)
db.close()
